spring:
  application:
     name: library-service
server:
  port: 3333
security:
  sessions: NEVER
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
      clientId: my-client
      clientSecret: my-client-secret
    resource:
      userInfoUri: http://localhost:9999/user